[package]
authors = ["Adam <adam@hodgen.uk>"]
name = "token"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.4"
rocket = "0.2.2"
rocket_codegen = "0.2.2"
rocket_contrib = "0.2.2"
serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"
